Core6Music/Core6Music.Web/Areas/Dashboard/ViewModels/AllAlbumViewModels.cs
using Core6Music.Web.DateContext.Enum;
using Core6Music.Web.Models;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Core6Music.Web.Areas.Dashboard.ViewModels
{
    public class AllAlbumViewModels
    {
        public IEnumerable<Album> AllAlbum { get; set; }
        [DisplayName("ID")]
        public string Id { get; set; }
        [DisplayName("名字")]
        public string Name { get; set; }
        [DisplayName("藝人")]
        public string ArtistId { get; set; }
        public Artist Artist { get; set; }
        [DisplayName("圖片")]
        public string Image { get; set; }
        [DisplayName("分類")]
        public AlbumCategory albumCategory { get; set; }
    }
}

Core6Music/Core6Music.Web/ViewModels/AlbumDetailViewModels.cs
using Core6Music.Web.Models;

namespace Core6Music.Web.ViewModels
{
    public class AlbumDetailViewModels
    {
        public IEnumerable<Album> albums { get; set; }
        public Album album { get; set; }
        public IEnumerable<Artist> artists { get; set; }
    }
}

Core6Music/Core6Music.Web/Controllers/MusicController.cs
using Microsoft.AspNetCore.Mvc;
using Core6Music.Web.DateContext;
using NToastNotify;
using Core6Music.Web.Models;
using Core6Music.Web.ViewModels;
using Microsoft.EntityFrameworkCore;
using Core6Music.Web.Interface;
using NuGet.Protocol.Plugins;
using Core6Music.Web.DateContext.Enum;

namespace Core6Music.Web.Controllers
{
    public class MusicController : Controller
    {
        private readonly MusicDateContext _musicDateContext;
        private readonly IToastNotification _toastNotify;

        public MusicController(MusicDateContext musicDateContext, IToastNotification toastNotification)
        {
            _musicDateContext= musicDateContext;
            _toastNotify= toastNotification;
        }
        public async Task<IActionResult> Index()
        {
            
            var AllAlbum =await  _musicDateContext.Albums.Include(artist => artist.Artist).Take(10).ToListAsync();
            var AllArtist = await _musicDateContext.Artists.
                Include(x => x.artistContextImages).
                Include(x => x.artistBackImages).
                Include(x => x.artistHeadImages).
                Include(album => album.albums).Take(10).
                ToListAsync();
            IndexMusciViewModels indexAlbumViewModels = new IndexMusciViewModels()
            {
                albums = AllAlbum,
                artists = AllArtist,
            };
            return View(indexAlbumViewModels);
        }

        [HttpGet("Artist/{ArtistID}")]
        public async Task<IActionResult> AritstDetail (string ArtistID)
        {
            var AritstModel = await _musicDateContext.Artists.AsNoTracking().
                Include(c=>c.artistContextImages).
                Include(b => b.artistBackImages).
                Include(h => h.artistHeadImages).
                Include(h => h.favoriteArtists).
                FirstOrDefaultAsync(x => x.Id == ArtistID);

            var songModel = await _musicDateContext.Songs.Include(x =>x.Album).Include(x => x.favoriteSongs).Where(x =>x.Album.ArtistId == ArtistID).Take(10).ToListAsync();
            var AlbumModel = await _musicDateContext.Albums.Where(x => x.ArtistId == ArtistID).Take(9).ToListAsync();
            IndexArtistVIewModel indexArtistVIewModel = new IndexArtistVIewModel()
            {
                songs = songModel,
                albums = AlbumModel,
                artist = AritstModel
            };
            return View(indexArtistVIewModel);
        }


        [HttpGet("Album/{AlbumId}")]
        public async Task<IActionResult> AlbumDetail(string AlbumId)
        {
            
            var TenAlbum = await _musicDateContext.Albums.Include(artist => artist.Artist).Take(10).ToListAsync();
            var album = await _musicDateContext.Albums.Include(x => x.favoriteAlbums).Include(x=>x.songs).ThenInclude(x => x.favoriteSongs).FirstOrDefaultAsync(x => x.Id == AlbumId);
            var AllAritst = await _musicDateContext.Artists.ToListAsync();
            AlbumDetailViewModels albumDetailViewModels = new AlbumDetailViewModels()
            {
                albums = TenAlbum,
                album = album,
                artists = AllAritst,
            };
            return View(albumDetailViewModels);
        }

        [HttpGet("Artist/{ArtistID}/AllAlbum")]
        public async Task<IActionResult> ArtistAllAlbum(string ArtistID)
        {
            var AllAlbum = await _musicDateContext.Albums.Include(song => song.songs).ThenInclude(x => x.favoriteSongs).Where(x =>x.ArtistId == ArtistID).Include(x => x.favoriteAlbums).ToListAsync();
            return View(AllAlbum);
        }
    }
}

Core6Music/Core6Music.Web/Controllers/MusicUserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Core6Music.Web.Models;
using Core6Music.Web.DateContext;
using NToastNotify;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using Core6Music.Web.ViewModels;
using NuGet.ContentModel;

namespace Core6Music.Web.Controllers
{
    public class MusicUserController : Controller
    {
        private readonly UserManager<MusicUser> _userManager;
        private readonly SignInManager<MusicUser> _SignInManager;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly MusicDateContext _musicDateContext;
        private readonly IToastNotification _toastNotification;

        public MusicUserController(UserManager<MusicUser> userManager, SignInManager<MusicUser> SignInManager, IWebHostEnvironment webHostEnvironment,MusicDateContext musicDateContext,IToastNotification toastNotification)
        {
            _SignInManager = SignInManager;
            _userManager = userManager; 
            _webHostEnvironment = webHostEnvironment;
            _musicDateContext = musicDateContext;
            _toastNotification = toastNotification;
        }
  

        public async Task<IActionResult> FavoriteAlbum()
        {
            
            if (_SignInManager.IsSignedIn(User))
            {
                IdentityUser sUser = await _userManager.GetUserAsync(User);
                var AllFavoriteAlbum = await _musicDateContext.FavoriteAlbums.Include(x =>x.Album).ThenInclude(x=> x.songs).Where(x => x.MusicUserId == sUser.Id).ToListAsync();
                return View(AllFavoriteAlbum);
            }

            return RedirectToAction("Index", "Music");
        }

        public async Task<IActionResult> FavoriteArtists()
        {

            if (_SignInManager.IsSignedIn(User))
            {
                IdentityUser sUser = await _userManager.GetUserAsync(User);
                var AllFavoriteArtists = await _musicDateContext.FavoriteArtists.Where(x => x.MusicUserId == sUser.Id).Include(x=>x.Artist).ThenInclude(x => x.artistHeadImages).ToListAsync();
                return View(AllFavoriteArtists);
            }
            return RedirectToAction("Index", "Music");
        }

        public async Task<IActionResult> FavoriteSong()
        {

            if (_SignInManager.IsSignedIn(User))
            {
                IdentityUser sUser = await _userManager.GetUserAsync(User);
                var AllFavoriteArtists = await _musicDateContext.FavoriteSongs.Where(x => x.MusicUserId == sUser.Id).Include(x => x.Song).ThenInclude(x => x.Album).ToListAsync();
                return View(AllFavoriteArtists);
            }
            return RedirectToAction("Index", "Music");
        }

        public async Task<IActionResult> AllPlayList()
        {
            AllPlayListViewModels allPlayListViewModels = new AllPlayListViewModels();
            if (_SignInManager.IsSignedIn(User))
            {
                IdentityUser AUser = await _userManager.GetUserAsync(User);

                var MusicPlayList = await _musicDateContext.MusicManifests.Include(x => x.musicManifestSongs).Where(x => x.MusicUserId == AUser.Id).ToListAsync();

                var favoriteMusic = await _musicDateContext.FavoriteSongs.Where(x => x.MusicUserId == AUser.Id).ToListAsync();
                allPlayListViewModels.musicManifests = MusicPlayList;
                allPlayListViewModels.favoriteSongs = favoriteMusic;
                return View(allPlayListViewModels);
            }

            return RedirectToAction("Index", "Music");
        }
        public async Task<IActionResult> DetailPlayList(int Id ,string? SearchSong)
        {
            DetailPlayListViewModels detailPlayListViewModels = new DetailPlayListViewModels();
            if (_SignInManager.IsSignedIn(User))
            {
                IdentityUser AUser = await _userManager.GetUserAsync(User);
                var DetailPlayList = await _musicDateContext.MusicManifests.Include(x => x.musicManifestSongs)
                    .Where(x => x.MusicUserId == AUser.Id)
                    .Where(x => x.Id == Id)
                    .FirstOrDefaultAsync();

                var DetailPlayListSong = await _musicDateContext.MusicManifestSongs.
                    Include(x => x.Song)
                    .ThenInclude(x => x.favoriteSongs)
                    .Include(x => x.Album)
                    .Where(x => x.MusicManifestId == DetailPlayList.Id).ToArrayAsync();

                if (SearchSong == null)
                {
                    detailPlayListViewModels.Songs = null;
                }
                else
                {
                    detailPlayListViewModels.Songs = await _musicDateContext.Songs.Include(x=> x.favoriteSongs).Include(x => x.Album).Where(x => x.Name == SearchSong).Take(10).ToListAsync();
                }
                detailPlayListViewModels.MusicManifest = DetailPlayList;
                detailPlayListViewModels.MusicManifestSongs = DetailPlayListSong;


                return View(detailPlayListViewModels);
            }
            return RedirectToAction("Index", "Music");

        }

        public async Task<JsonResult> CreatePlayList()
        {
            bool Result = false;
            if (_SignInManager.IsSignedIn(User))
            {
                IdentityUser identityUser = await _userManager.GetUserAsync(User);
                MusicManifest musicManifest = new MusicManifest
                {
                    MusicUserId = identityUser.Id,
                };
                _musicDateContext.Add(musicManifest);
                Result = await _musicDateContext.SaveChangesAsync() > 0;
            }

            if (Result)
            {
                return Json(new { Success = true });
            }
            else
            {
                return Json(new { Success = false });
            }
            
        }

        [HttpPost]
        public async Task<JsonResult> EditPlayList(int Id, [Bind("Name,Context")] MusicManifest musicManifest ,IFormFile formFile)
        {
            bool Result = false;
            string FileName;
            if (_SignInManager.IsSignedIn(User))
            {
                IdentityUser identityUser = await _userManager.GetUserAsync(User);
                var PlayListEdit = await _musicDateContext.MusicManifests.AsNoTracking().Where(x => x.MusicUserId == identityUser.Id).Where(x => x.Id == Id).FirstOrDefaultAsync();

                if(formFile == null)
                {
                    FileName = PlayListEdit.Image;
                }
                else
                {
                    string SPath = Path.Combine(_webHostEnvironment.WebRootPath, "Image/PlayList");
                    if (!Directory.Exists(SPath))
                    {
                        Directory.CreateDirectory(SPath);
                    }

                    FileName = Guid.NewGuid().ToString() + "-" + formFile.FileName;
                    string PathFile = Path.Combine(SPath, FileName);
                    using (var steam = new FileStream(PathFile, FileMode.Create))
                    {
                        formFile.CopyTo(steam);
                    }
                }
               

                    MusicManifest EditmusicManifest = new MusicManifest
                    {
                        Id = Id,
                        MusicUserId = identityUser.Id,
                        Name= musicManifest.Name,
                        Context = musicManifest.Context,
                        Image = FileName
                    };
                _musicDateContext.Update(EditmusicManifest);
                Result = await _musicDateContext.SaveChangesAsync() > 0;
               
            }
            if (Result)
            {
                _toastNotification.AddSuccessToastMessage("成功!");
                return Json(new { Success = true });
            }
            else
            {
                _toastNotification.AddSuccessToastMessage("失敗!");
                return Json(new { Success = false });
            }
        }
        public async Task<JsonResult> DeletePlayList(int Id)
        {
            bool Result = false;
            if (_SignInManager.IsSignedIn(User))
            {
                IdentityUser user = await _userManager.GetUserAsync(User);
                var DeletePlayList = await _musicDateContext.MusicManifests.Include(x => x.musicManifestSongs).Where(x => x.MusicUserId == user.Id).Where(x => x.Id == Id).FirstOrDefaultAsync();

                if(DeletePlayList.Image != null)
                {
                    string DeleteImage = Path.Combine(_webHostEnvironment.WebRootPath, "Image/PlayList", DeletePlayList.Image);
                    if (Directory.Exists(DeleteImage)){
                        Directory.Delete(DeleteImage);
                    };
                };
                

                _musicDateContext.Remove(DeletePlayList);
                Result = await _musicDateContext.SaveChangesAsync() > 0;


            }
            if (Result)
            {
                _toastNotification.AddSuccessToastMessage("成功!");
                return Json(new { Success = true });
            }
            else
            {
                _toastNotification.AddSuccessToastMessage("失敗!");
                return Json(new { Success = false });
            }
        }


        public async Task<JsonResult> AddorDeleteSongPlayList(int MusicMainfestId,int SongId,string AlbumId)
        {
            var SongPlayList = await _musicDateContext.MusicManifestSongs.Include(x => x.MusicManifest).Where(x => x.MusicManifestId == MusicMainfestId).Where(x => x.SongId == SongId).FirstOrDefaultAsync();

Core6Music/Core6Music.Web/Views/Music/AlbumDetail.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Core6Music.Web.ViewModels.AlbumDetailViewModels
@using Core6Music.Web.DateContext.Enum;
@using Microsoft.AspNetCore.Identity;


@inject SignInManager<MusicUser> SignInManager
@inject UserManager<MusicUser> UserManager
@{
    string AbPath = "~/Image/Album/";
    string mp3Path = "/MP3/";
    TimeSpan AlbumTotatl =new TimeSpan(Model.album.songs.Sum(x => x.SongTime.Ticks));
    IdentityUser user = await UserManager.GetUserAsync(User);
}
<div class="container py-4">


    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">@Model.album.Name</h1>
            @if (user != null)
            {
                @if(Model.album.favoriteAlbums.FirstOrDefault() != null)
                {
                    <button onclick="FavoriteAlbum('@Url.Action("AddorDeleteFavoriteAlbum","MusicUser",new{Id = Model.album.Id})')">取消關注</button>
                }
                else
                {
                    <button onclick="FavoriteAlbum('@Url.Action("AddorDeleteFavoriteAlbum","MusicUser",new{Id = Model.album.Id})')">關注</button>
                } 
            }
          
            
           
            <img asp-append-version="true" width="500px" height="300px" src="@(AbPath + Model.album.Image)" />
        </div>
    </div>

    <h1 class="display-4">歌曲</h1>
    <p>
       
        @AlbumTotatl.Hours 小時 @AlbumTotatl.Minutes 分鐘 @AlbumTotatl.Seconds 秒
    </p>
    <div class="bd-example">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">名字</th>
                    <th scope="col"></th>
                    <th scope="col">時間長度</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.album.songs)
                {

                    <tr>
                        <td>
                            <div class="container bd-example-row text-center">
                                <div class="row">
                                    <div class="text-center col">
                                        <img src="@(AbPath+item.Album.Image)" width="40px" height="40px" asp-append-version="true">

                                    </div>



                                </div>
                            </div>

                        </td>
                        <td>
                            <div class="container bd-example-row text-center">
                                <div class="row">
                                    <div class="text-center col">
                                        <p>@item.Name</p>

                                    </div>



                                </div>
                            </div>

                        </td>
                        <td>
                            <div class="text-center col text-center">
                                <p>@item.ArtistName</p>
                            </div>
                        </td>
                        <td>
                            <div>
                                <audio controls="controls" src="@(mp3Path + item.Mp3NameFile)" preload="none">


                                    Your browser does not support this audio format.
                                </audio>
                            </div>
                        </td>
                        <td>
                            <div>
                                @item.SongTime.Minutes : @item.SongTime.Seconds
                            </div>
                        </td>
                        @if(user != null)
                        {
                              @if (item.favoriteSongs.Where(x => x.MusicUserId == user.Id).Where(x => x.SongId == item.Id).FirstOrDefault() != null)
                            {
                                <td>
                                    <div>
                                        <button onclick="FavoriteSong('@Url.Action("AddorDeleteFavoriteSong","MusicUser",new{Id = item.Id})')">取消喜歡</button> FavoriteSong
                                    </div>
                                </td>
                            }
                            else
                            {
                                <td>
                                    <div>
                                        <button onclick="FavoriteSong('@Url.Action("AddorDeleteFavoriteSong","MusicUser",new{Id = item.Id})')">喜歡</button> FavoriteSong
                                    </div>
                                </td>
                            }  
                        }
                        
                    </tr>
                }

            </tbody>

        </table>
    </div>



    <script>
        var audios = document.getElementsByTagName("audio");
        // 暂停函数
        function pauseAll() {
            var self = this;
            [].forEach.call(audios, function (i) {
                // 将audios中其他的audio全部暂停
                i !== self && i.pause();
            })
        }
        // 给play事件绑定暂停函数
        [].forEach.call(audios, function (i) {
            i.addEventListener("play", pauseAll.bind(i));
        })

        FavoriteAlbum = (url) =>{
            $.ajax({
                type:"get",
                url : url,
                success: function(res){
                    if(res.success){
                        location.reload();
                    }
                }
            })
        }
        FavoriteSong = (url) => {
            $.ajax({
                type: "get",
                url: url,
                success: function (res) {
                    if (res.success) {
                        location.reload();
                    }
                }
            })
        }
    </script>

Core6Music/Core6Music.Web/Views/Music/AllAlbum.cshtml
@model IEnumerable<Core6Music.Web.Models.Album>
@using Core6Music.Web.DateContext.Enum;

@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    string AbiumPath = "~/Image/Album/";
}
<div class="row row-cols-1 row-cols-md-3 g-4">
    @foreach (var item in Model)
    {
        <div class="col">
            <div class="card" style="width: 18rem;">
                <img src="@(AbiumPath+item.Image)" asp-append-version="true" class="card-img-top" />
                <div class="card-body">
                    <h5 class="card-title">@item.Name</h5>
                    <p class="card-text">@((AlbumCategory)item.albumCategory)</p>
                    <a asp-action="AlbumDetail" asp-route-AlbumId="@item.Id" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
        </div>
    }
</div>

Core6Music/Core6Music.Web/Views/Music/ArtistAllAlbum.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<Core6Music.Web.Models.Album>
@using Core6Music.Web.DateContext.Enum;
@using Microsoft.AspNetCore.Identity;

@inject SignInManager<MusicUser> SignInManager
@inject UserManager<MusicUser> UserManager
@{
    string AbPath = "~/Image/Album/";
    string mp3Path = "~/MP3/";
    var user = await UserManager.GetUserAsync(User);
}

@foreach(var item in Model)
{
<div class="container col-xxl-8 px-4 py-5">
    <div class="row flex-lg-row-reverse align-items-center g-5 py-5">
      <div class="col-10 col-sm-8 col-lg-6">
        <img src="@(AbPath + item.Image)" class="d-block mx-lg-auto img-fluid" asp-append-version="true" alt="Bootstrap Themes" width="700" height="500" loading="lazy">
      </div>
      <div class="col-lg-6">
        <h1 class="display-5 fw-bold lh-1 mb-3">@item.Name</h1>
        <p class="lead">@((AlbumCategory)item.albumCategory).@item.songs.Count() 首歌曲</p>
        <div class="d-grid gap-2 d-md-flex justify-content-md-start">
                    @if(user != null)
                    {
                        @if(item.favoriteAlbums.Where(x => x.MusicUserId ==user.Id).Where(x => x.AlbumId ==item.Id).FirstOrDefault() != null)
                        {
                            <button type="button" onclick="favortAlbum('@Url.Action("AddorDeleteFavoriteAlbum","MusicUser",new {Id = item.Id})')" class="btn btn-primary btn-lg px-4 me-md-2">取消關注</button>
                        }
                        else
                        {
                            <button type="button" onclick="favortAlbum('@Url.Action("AddorDeleteFavoriteAlbum","MusicUser",new {Id = item.Id})')" class="btn btn-primary btn-lg px-4 me-md-2">關注</button>
                       
                        }                        
                    }

                
        </div>
      </div>
    </div>
  </div>
    <div class="bd-example">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">名字</th>
                    <th scope="col"></th>
                    <th scope="col">時間長度</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var Mitem in item.songs)
                {
                    <tr>

                        <td>
                            <div class="container bd-example-row text-center">
                                <div class="row">
                                    <div class="text-center col">
                                        <img src="@(AbPath+Mitem.Album.Image)" width="40px" height="40px" asp-append-version="true">

                                    </div>



                                </div>
                            </div>

                        </td>
                        <td>
                            <div class="text-center col text-center">
                                <p>@Mitem.Name</p>
                            </div>
                        </td>
                        <td>
                            <div>
                                <audio controls="controls" src="@(mp3Path + Mitem.Mp3NameFile)" preload="none">


                                    Your browser does not support this audio format.
                                </audio>
                            </div>
                        </td>
                        <td>
                            <div>
                                @Mitem.SongTime.Minutes : @Mitem.SongTime.Seconds
                            </div>
                        </td>
                        @if(user != null)
                        {
                            @if (Mitem.favoriteSongs.Where(x => x.MusicUserId == user.Id).Where(x => x.SongId == Mitem.Id).FirstOrDefault() != null)
                            {
                                <td>
                                    <div>
                                        <button onclick="FavoriteSong('@Url.Action("AddorDeleteFavoriteSong","MusicUser",new{Id = Mitem.Id})')">取消喜歡</button> FavoriteSong
                                    </div>
                                </td>
                            }
                            else
                            {
                                <td>
                                    <div>
                                        <button onclick="FavoriteSong('@Url.Action("AddorDeleteFavoriteSong","MusicUser",new{Id = Mitem.Id})')">喜歡</button> FavoriteSong
                                    </div>
                                </td>
                            }  
                        }
                       
                    </tr>


                   
                }

            </tbody>

        </table>
    </div>
}
<script>
    var audios = document.getElementsByTagName("audio");
    // 暂停函数
    function pauseAll() {
        var self = this;
        [].forEach.call(audios, function (i) {
            // 将audios中其他的audio全部暂停
            i !== self && i.pause();
        })
    }
    // 给play事件绑定暂停函数
    [].forEach.call(audios, function (i) {
        i.addEventListener("play", pauseAll.bind(i));
    })

    favortAlbum = (url) =>{
        $.ajax({
            type:"get",
            url: url,
            scuccess:function(res){
                if(res.success){
                    location.reload();
                }
            }
        })
    }


    favortSong = (url) =>{
        $.ajax({
            type:"get",
            url: url,
            scuccess:function(res){
                if(res.success){
                    location.reload();
                }
            }
        })
    }
</script>

Core6Music/Core6Music.Web/Views/Music/Index.cshtml
@model Core6Music.Web.ViewModels.IndexMusciViewModels
@using Core6Music.Web.DateContext.Enum
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    DateTime dateTime = DateTime.Now.ToLocalTime();
    string AbiumPath = "~/Image/Album/";
    string HeadArtistPath = "~/Image/Artist/HeadImage/";
}

@if(dateTime.Hour <= 12  ){
    <h1> 早安</h1>
}
else if (dateTime.Hour > 12 && dateTime.Hour < 17){
    <h1> 午安</h1>
}else{
    <h1> 晚安</h1>
}
<h1 class="display-4">專輯</h1>
<div class="row row-cols-1 row-cols-md-3 g-4">
@foreach(var item in Model.albums){
     <div class="col">
            <div class="card" style="width: 18rem;">
                <img src="@(AbiumPath+item.Image)"width="100px" height="300px"  asp-append-version="true" class="card-img-top"/>
                <div class="card-body">
                    <h5 class="card-title">@item.Name</h5>
                    <p class="card-text">@((AlbumCategory)item.albumCategory)</p>
                    <a asp-action="AlbumDetail" asp-route-AlbumId="@item.Id" class="btn btn-primary">Go somewhere</a>
                </div>
            </div>
    </div>
}
</div>
<h1 class="display-4">藝人</h1>
<div class="row row-cols-1 row-cols-md-3 g-4">
@foreach (var item in Model.artists)
    {
    <div class="col">
        <div class="card" style="width: 18rem;">
                @if (item.artistHeadImages != null)
                {
                    <img src="@(HeadArtistPath+item.artistHeadImages.ImageName)"width="100px" height="300px"  asp-append-version="true" class="card-img-top" />
                }
                else
                {
                   <img src="" asp-append-version="true" class="card-img-top" />
                }
                
         
            <div class="card-body">
                <h5 class="card-title">@item.Name</h5>
                
                <a asp-action="AritstDetail" asp-route-ArtistID="@item.Id" class="btn btn-primary">Go somewhere</a>
            </div>
        </div>
    </div>
}

</div>