Core6Music/Core6Music.Web/Models/Album.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using Core6Music.Web.DateContext.Enum;

namespace Core6Music.Web.Models
{
    [Table("Album",Schema ="dbo")]
    public class Album
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string ArtistId { get; set; }
        public Artist Artist { get; set; }
        public string Image { get; set; }
        public AlbumCategory albumCategory { get; set; }

        public ICollection<Song> songs { get; set; }
        public ICollection<FavoriteAlbum> favoriteAlbums { get; set; }

        public ICollection<MusicManifestSong> musicManifestSongs { get; set; }
    }
}

Core6Music/Core6Music.Web/Areas/Dashboard/Controllers/AlbumsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Core6Music.Web.DateContext;
using Core6Music.Web.Models;
using Core6Music.Web.Interface;
using Core6Music.Web.Areas.Dashboard.ViewModels;
using HashidsNet;
using NToastNotify;

namespace Core6Music.Web.Areas.Dashboard.Controllers
{
    [Area("Dashboard")]
    public class AlbumsController : Controller
    {
        private readonly MusicDateContext _context;
        private readonly IAlbum _album;
        private readonly IToastNotification _toastNotification;
        public AlbumsController(MusicDateContext context,IAlbum album, IToastNotification toastNotification)
        {
            _context = context;
            _album = album;
            _toastNotification = toastNotification;
        }

        // GET: Dashboard/Albums
        [HttpGet("Dashboard/{ArtistId}/Albums")]
        public async Task<IActionResult> Index(string ArtistId)
        {
            AllAlbumViewModels allAlbumViewModels = new AllAlbumViewModels()
            {
                AllAlbum = await _album.GetAllAlbum(ArtistId),
                ArtistId = ArtistId
            };
            return View(allAlbumViewModels);
        }

        // GET: Dashboard/Albums/Details/5
        [HttpGet("Dashboard/{ArtistId}/Albums/{id}")]
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Albums == null)
            {   
                return NotFound();
            }
            var album = await _album.GetAlbum(id);
           
          
            if (album == null)
            {
                return NotFound();
            }

            return View(album);
        }

        [HttpGet("Dashboard/{ArtistId}/Albums/Create")]
        // GET: Dashboard/Albums/Create
        public IActionResult Create()
        {
            
            return View();
        }

        // POST: Dashboard/Albums/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("Dashboard/{ArtistId}/Albums/Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Name,albumCategory,Image")] CreateAlbumViewModels createAlbumViewModels,string ArtistId)
        {
            if (ModelState.IsValid)
            {
               
                var hash = new Hashids(createAlbumViewModels.Name + ArtistId, 22);
                var hashId = hash.Encode(1);
              

                Album album = new Album()
                {
                    Id = hashId,
                    Name = createAlbumViewModels.Name,
                    ArtistId = ArtistId,
                    albumCategory = createAlbumViewModels.albumCategory,
                    Image = _album.SaveImage(createAlbumViewModels.Image)
                };
                if (_album.CreateAlbum(album))
                {
                    _toastNotification.AddSuccessToastMessage("儲存成功!");
                    return RedirectToAction(nameof(Index), new { ArtistId = ArtistId });
                }
                
            }
          
            return View(createAlbumViewModels);
        }

        [HttpGet("Dashboard/{ArtistId}/Albums/Edit/{id}")]
        // GET: Dashboard/Albums/Edit/5
        public async Task<IActionResult> Edit(string id,string ArtistId)
        {
            if (id == null || _context.Albums == null)
            {
                return NotFound();
            }

            var album = await _album.GetAlbum(id);
            EditAlbumViewModels editAlbumViewModels = new EditAlbumViewModels
            {
                Id = album.Id,
                Name = album.Name,
                
                ImageName = album.Image,
                albumCategory = album.albumCategory
            };
            if (album == null)
            {
                return NotFound();
            }
          
            return View(editAlbumViewModels);
        }

        // POST: Dashboard/Albums/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost("Dashboard/{ArtistId}/Albums/Edit/{id}")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id,string ArtistId,[Bind("Id,Name,albumCategory,Image")] EditAlbumViewModels editAlbumViewModels)
        {
            if (id != editAlbumViewModels.Id)
            {
                return NotFound();
            }
           

            if (ModelState.IsValid)
            { 
               
                try
                {
                    Album album = new Album()
                    {
                        Id = editAlbumViewModels.Id,
                        Name = editAlbumViewModels.Name,
                        albumCategory = editAlbumViewModels.albumCategory,
                        ArtistId = ArtistId,
                    };

                    Album EditeImage = await _album.GetAlbum(editAlbumViewModels.Id);
                    if (editAlbumViewModels.Image != null )
                    {
                        
                        if (EditeImage.Image != null)
                        {
                           _album.DeleteImage(EditeImage.Image);
                           album.Image = _album.SaveImage(editAlbumViewModels.Image);

                        }
                        else
                        {
                            album.Image = _album.SaveImage(editAlbumViewModels.Image);
                        }
                        
                    }else
                    {
                        album.Image = EditeImage.Image;
                    }
                   

                    _album.EditAlbum(id, album);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AlbumExists(editAlbumViewModels.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                _toastNotification.AddSuccessToastMessage("更新成功!!");
                return RedirectToAction(nameof(Index), new { ArtistId = ArtistId });
            }
            _toastNotification.AddErrorToastMessage("更新失敗!!");
            return View(editAlbumViewModels);
        }

        // GET: Dashboard/Albums/Delete/5
        [HttpGet("Dashboard/{ArtistId}/Albums/Delete/{id}")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Albums == null)
            {
                return NotFound();
            }

            var album = await _album.GetAlbum(id);
            if (album == null)
            {
                return NotFound();
            }

            return View(album);
        }

        // POST: Dashboard/Albums/Delete/5
        [HttpPost("Dashboard/{ArtistId}/Albums/Delete/{id}"), ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id,string ArtistId)
        {
            if (_context.Albums == null)
            {
                return Problem("Entity set 'MusicDateContext.Albums'  is null.");
            }
            var album = await _album.GetAlbum(id);

            if(album.Image != null && album != null)
            {
                _album.DeleteImage(album.Image);
            }

            if (album != null &&_album.DeleteAlbum(id))
            {
                _toastNotification.AddSuccessToastMessage("刪除成功!!");
                return RedirectToAction(nameof(Index),new { ArtistId= ArtistId });
            }
            else
            {
                _toastNotification.AddErrorToastMessage("刪除失敗!!");
                return RedirectToAction("Edit", album.Id);
            }
            
          
          
        }

        private bool AlbumExists(string id)
        {
          return _context.Albums.Any(e => e.Id == id);
        }
    }
}

Core6Music/Core6Music.Web/Areas/Dashboard/Views/Albums/Create.cshtml
@model Core6Music.Web.Areas.Dashboard.ViewModels.CreateAlbumViewModels

@using Core6Music.Web.DateContext.Enum;
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Album</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" asp-controller="Albums" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" type="file" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="albumCategory" class="control-label"></label>
                <select asp-for="albumCategory" class="form-control" asp-items="Html.GetEnumSelectList<AlbumCategory>()"></select>
                <span asp-validation-for="albumCategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Core6Music/Core6Music.Web/Areas/Dashboard/Views/Albums/Delete.cshtml
@model Core6Music.Web.Models.Album

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Album</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artist.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Image)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.albumCategory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.albumCategory)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Core6Music/Core6Music.Web/Areas/Dashboard/Views/Albums/Details.cshtml
@model Core6Music.Web.Models.Album
@using Core6Music.Web.DateContext.Enum;

@{
    ViewData["Title"] = "Details";
    string path = "~/Image/Album/";
}

<h1>Details</h1>

<div>
    <h4>Album</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Artist)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Artist.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Image)
        </dt>
        <dd class = "col-sm-10">
            <img src="@(path + Model.Image)" asp-append-version="true" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.albumCategory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.albumCategory)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Core6Music/Core6Music.Web/Areas/Dashboard/Views/Albums/Edit.cshtml
@model Core6Music.Web.Areas.Dashboard.ViewModels.EditAlbumViewModels
@using Core6Music.Web.DateContext.Enum;
@{
    ViewData["Title"] = "Edit";
    string Path = "~/Image/Album/";
}

<h1>Edit</h1>

<h4>Album</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data" method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
           

            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
           
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
               <img src="@(Path + Model.ImageName)" asp-append-version="true"/>
                <input asp-for="Image" type="file" class="form-control" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="albumCategory" class="control-label"></label>
                <select asp-for="albumCategory" class="form-control" asp-items="Html.GetEnumSelectList<AlbumCategory>()"></select>
                <span asp-validation-for="albumCategory" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Core6Music/Core6Music.Web/Areas/Dashboard/Views/Albums/Index.cshtml
@model Core6Music.Web.Areas.Dashboard.ViewModels.AllAlbumViewModels

@{
    ViewData["Title"] = "Index";
    string Path = "~/Image/Album/";

}
<h1>Index</h1>

<p>
    <a asp-action="Create" asp-route-ArtistId=@Model.ArtistId>新增</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Artist)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.albumCategory)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.AllAlbum) {
        <tr>
            
            <td width="500px" >
                <div class="container bd-example-row text-center">
                    <div class="row ">
                        <div class="text-center col">
                            <img src="@(Path + item.Image)" width="100%" height="100%" asp-append-version="true">
                        </div>
                        <div class="text-center col text-center">
                            <p>@item.Name</p>
                        </div>
                    </div>
                </div>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Artist.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.albumCategory)
            </td> 
            <td>
                    @if(item.songs.Count() == 0)
                    {
                        <a asp-action="Create" asp-controller="Songs" asp-route-AdlumId="@item.Id" >新增音樂</a>
                        
                    }else{
                        <a asp-action="Index" asp-controller="Songs" asp-route-AdlumId="@item.Id">@item.songs.Count()首</a>
                    }
                </td>
            <td>
                    <a asp-action="Edit" asp-route-ArtistId="@item.Artist.Id" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-ArtistId="@item.Artist.Id" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-ArtistId="@item.Artist.Id" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>